 function[] = set_teensy_parameters(s,tp)

 param_stem =  '<P,'; % e.g., '<P,1,0>', select parameter 1, set it to 0 or fals

 parameter_codes = ...
 {{'enforceEarlyLick',  1}; ... 
  {'lickMax',           2}; ...
  {'waitForNextFrame',  3}; ...
  {'contingentStim',    4}; ...
  {'trigLen',           5}; ...
  {'respLen',           6}; ...
  {'valveLen',          7}; ... 
  {'consumeLen',        8}; ...
  {'pairDelay',         9}; ...
  {'outLen',          10}; ...
  {'removeLen',         11}};

 fns = fieldnames(tp);

 for i = 1:numel(fns)
     param_code = parameter_codes{cellfun(@(x) strcmp(x(1),fns{i}),parameter_codes,'uniformOutput',true)}{2};
     param_val = tp.(fns{i});
     fprintf(['\n' param_stem num2str(param_code) ',' num2str(param_val) '>'])
     write(s,[param_stem num2str(param_code) ',' num2str(param_val) '>'],'string'); % set each parameter on teensy
     pause(0.1);
 end
